---
roles:
- src: ten7.flightdeck_base
  version: 5.1.3
- src: ten7.digitalocean
- src: ten7.digitalocean_kubeconfig
- src: ten7.digitalocean_domain
  version: 1.1.0
- src: ten7.flightdeck_cluster
  version: 1.4.9
- src: ten7.tugboat_repo
  version: 1.0.1
collections:
  - name: community.kubernetes
