---
- hosts: flight_deck_util
  tasks:
    - name: Create a temp directory to store files needed by the run
      tempfile:
        state: directory
        prefix: "ansible-deploy-"
      register: _run_temp_dir
      notify:
        - clear caches
    - name: Do base configuration
      include_role:
        name: "ten7.flightdeck_base"
    - name: Install needed software
      apk:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - "bash"
        - "ca-certificates"
        - "libcap"
        - "zlib"
        - "git"
        - "patch"
        - "curl"
        - "mariadb-client"
        - "rsync"
        - "rclone"
        - "openssh-client"
        - "python3"
        - "py3-urllib3"
        - "py3-mysqlclient"
        - "py3-jmespath"
        - "py3-certifi"
        - "py3-requests"
        - "tar"
      notify:
        - clear caches
    - name: Install s3cmd
      shell: >
        apk add s3cmd --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing
    - name: Install build dependencies in a virtual package
      shell: >
        apk --no-cache \
            --virtual flightdeck-build \
             add py3-pip \
                 py3-setuptools \
                 python3-dev \
                 py3-setuptools \
                 linux-headers \
                 g++
      notify:
        - uninstall build deps
    - name: Install the additional packages from pip
      pip:
        name:
          - "passlib"
          - "openshift==0.11.0"
        extra_args: "--no-cache-dir"
    - name: Get the stable version of Kubectl
      get_url:
        url: "https://storage.googleapis.com/kubernetes-release/release/stable.txt"
        dest: "{{ _run_temp_dir.path }}/stable.txt"
    - name: Download kubectl
      get_url:
        url: "https://storage.googleapis.com/kubernetes-release/release/{{ lookup('file', _run_temp_dir.path + '/stable.txt' )}}/bin/linux/amd64/kubectl"
        dest: "/bin/kubectl"
        owner: "root"
        group: "util"
        mode: "u=rwx,g=rx,o="
    - name: Download helm
      get_url:
        url: "https://get.helm.sh/helm-v3.1.0-rc.1-linux-amd64.tar.gz"
        dest: "{{ _run_temp_dir.path }}/helm.tar.gz"
        owner: "root"
        group: "util"
        mode: "u=rwx,g=rx,o="
    - name: Expand helm archive
      unarchive:
        remote_src: no
        src: "{{ _run_temp_dir.path }}/helm.tar.gz"
        dest: "{{ _run_temp_dir.path }}/"
        creates: "{{ _run_temp_dir.path }}/linux-amd64/helm"
    - name: Install helm command
      copy:
        src: "{{ _run_temp_dir.path }}/linux-amd64/helm"
        dest: "/usr/local/bin/helm"
        owner: "root"
        group: "util"
        mode: "u=rx,g=rx,o="
    - name: Download Velero
      get_url:
        url: "https://github.com/vmware-tanzu/velero/releases/download/v1.5.3/velero-v1.5.3-linux-amd64.tar.gz"
        dest: "{{ _run_temp_dir.path }}/velero.tar.gz"
        owner: "root"
        group: "util"
        mode: "u=rwx,g=rx,o="
    - name: Expand Velero archive
      unarchive:
        remote_src: no
        src: "{{ _run_temp_dir.path }}/velero.tar.gz"
        dest: "{{ _run_temp_dir.path }}/"
        creates: "{{ _run_temp_dir.path }}/velero-v1.5.3-linux-amd64/velero"
    - name: Install velero command
      copy:
        src: "{{ _run_temp_dir.path }}/velero-v1.5.3-linux-amd64/velero"
        dest: "/usr/local/bin/velero"
        owner: "root"
        group: "util"
        mode: "u=rx,g=rx,o="
    - name: Add Helm repositories
      kubernetes.core.helm_repository:
        name: "{{ item.name }}"
        repo_url: "{{ item.repo_url }}"
      loop_control:
        label: "{{ item.name }}"
      loop:
        - name: "jetstack"
          repo_url: "https://charts.jetstack.io"
        - name: "ingress-nginx"
          repo_url: "https://kubernetes.github.io/ingress-nginx"
        - name: "flightdeck"
          repo_url: "https://ten7.github.io/flightdeck-operator"
        - name: "rook-release"
          repo_url: "https://charts.rook.io/release"

  handlers:
    - name: uninstall build deps
      shell: >
        apk del flightdeck-build
    - name: clear caches
      shell: >
        rm -rf {{ item }}
      args:
        warn: no
      loop:
        - "/tmp/*"
        - "/var/cache/apk/*"
        - "/var/www/.composer/cache"
        - "/var/www/.npm/_cacache"
        - "/root/.ansible/tmp"
        - "/root/.cache"
